api_workflow:
    resource: "@AbcWorkflowBundle/Controller/WorkflowController.php"
    type: rest
    prefix: /
api_workflow_tasks:
    resource: "@AbcWorkflowBundle/Controller/TaskController.php"
    type: rest
    name_prefix: api_
    parent: api_workflow
api_workflow_executions:
    resource: "@AbcWorkflowBundle/Controller/ExecutionController.php"
    type: rest
    name_prefix: api_
    parent: api_workflow